steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-west9-docker.pkg.dev/marketplace-deployment-487915/hello-world-python:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'europe-west9-docker.pkg.dev/marketplace-deployment-487915/hello-world-python:$SHORT_SHA']

  - name: google/cloud-sdk
    args: ['gcloud', 'run', 'deploy', 'hello-world-python', 
           '--image=europe-west9-docker.pkg.dev/marketplace-deployment-487915/hello-world-python:$SHORT_SHA', 
           '--region', 'europe-west9', '--platform', 'managed', 
           '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - europe-west9-docker.pkg.dev/marketplace-deployment-487915/hello-world-python:$SHORT_SHA
